# MongoDB
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user
      password: password
      username: admin
      authentication-database: admin
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_APP_CLIENT_ID}
            client-secret: ${GOOGLE_APP_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          custom:
            client-id: fooClientIdPassword
            client-secret: secret
            scopes: read
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8080/spring-security-oauth-server/oauth/authorize
            token-uri: http://localhost:8080/spring-security-oauth-server/oauth/token
            user-info-uri: http://localhost:8080/spring-security-oauth-resource/users/extra
            user-name-attribute: user_name
            redirect-uri: http://localhost:8080/login/oauth2/code/google

logging:
  level:
    org.springframework.data.mongodb: DEBUG

s3:
  config:
    region: ${AWS_DEFAULT_REGION}
    endpoint:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    bucket: booksyncapp
